### ISSUE TITLE
Can't compile on Linux

### ISSUE THREAD

**Issue by clizianthi** [dedesite/zig-nds-sample#1]
I tried to clone the repo and running `zig build` it throws this error:

```
install
└─ run /opt/wonderful/thirdparty/blocksds/core/tools/ndstool/ndstool
   └─ run /opt/wonderful/toolchain/gcc-arm-none-eabi/bin/arm-none-eabi-gcc
      └─ install generated to hello_world.o
         └─ zig build-obj hello-world Debug arm-freestanding-eabi 2 errors
src/hello_world.zig:1:11: error: C import failed
const c = @cImport({
          ^~~~~~~~
src/hello_world.zig:1:11: note: libc headers not available; compilation does not link against libc
referenced by:
    main: src/hello_world.zig:26:18
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/home/user/zig/zig-nds-sample/.zig-cache/o/62c28e09a55ac1986ea3f4fbd2b21430/cimport.h:3:10: error: 'nds/libversion.h' file not found
#include <nds/libversion.h>
         ^
error: the following command failed with 2 compilation errors:
/usr/bin/zig build-obj -ODebug -target arm-freestanding-eabi -mcpu arm9 -I /home/user/zig/opt/wonderful/thirdparty/blocksds/core/libs/libnds/include -I /home/user/zig/opt/wonderful/toolchain/gcc-arm-none-eabi/include -I /home/user/zig/opt/wonderful/toolchain/gcc-arm-none-eabi/arm-none-eabi/include -Mroot=/home/user/zig/zig-nds-sample/src/hello_world.zig --cache-dir /home/user/zig/zig-nds-sample/.zig-cache --global-cache-dir /home/user/.cache/zig --name hello-world --listen=-
Build Summary: 0/5 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ run /opt/wonderful/thirdparty/blocksds/core/tools/ndstool/ndstool transitive failure
   └─ run /opt/wonderful/toolchain/gcc-arm-none-eabi/bin/arm-none-eabi-gcc transitive failure
      └─ install generated to hello_world.o transitive failure
         └─ zig build-obj hello-world Debug arm-freestanding-eabi 2 errors
error: the following build command failed with exit code 1:
/home/user/zig/zig-nds-sample/.zig-cache/o/34e8d658ee080846dc5249cad44418dc/build /usr/bin/zig /home/user/zig/zig-nds-sample /home/user/zig/zig-nds-sample/.zig-cache /home/user/.cache/zig --seed 0x5bcf1574 -Zb164177ddddb3fa7
```

I have blocksds installed and set environment variables but very little experience with zig and its interoperability with C/C++

**Comment by dedesite** [comment]
Sorry, I lost all my data on my disk and my dev env so I need to reconfigure everything to try to help you.
Seems that zig can't link to the blocksd libc headers... The project was initially made for devkitpro and the blocksd was even more hacky so some path may be wrong or missing.
Try to find were are the blocksd libc headers and add them if missing, also maybe some include path are wrong... I was using NixOS and the Docker image from blocksd so it was certainly different from a "standard" linux install.
If I have time, I will try to look at it.

**Comment by Kuratius** [comment]
This may also be helpful: https://codeberg.org/GalaxyShard/zig-nds

**Comment by clizianthi** [comment]
> This may also be helpful: https://codeberg.org/GalaxyShard/zig-nds

oh yes I remember this but it involves using a forked version of the zig compiler and I didn't really liked it as an option, ty anyway

> Sorry, I lost all my data on my disk and my dev env so I need to reconfigure everything to try to help you. Seems that zig can't link to the blocksd libc headers... The project was initially made for devkitpro and the blocksd was even more hacky so some path may be wrong or missing. Try to find were are the blocksd libc headers and add them if missing, also maybe some include path are wrong... I was using NixOS and the Docker image from blocksd so it was certainly different from a "standard" linux install. If I have time, I will try to look at it.

no problem thanks anyway, I will continue on trying and eventually close/report back

**Comment by dedesite** [comment]
> This may also be helpful: https://codeberg.org/GalaxyShard/zig-nds

Thanks @Kuratius for the link, didn't know someone else tried to do that. It seems he got further than me.

> oh yes I remember this but it involves using a forked version of the zig compiler and I didn't really liked it as an option, ty anyway

It's only a fork of the standard build system and there is only [one commit](https://github.com/ziglang/zig/compare/master...GalaxyShard:zig:nds) on top of it. Maybe the things could be done without it.
I'm not working on zig right now, but I might eventualy use GalaxyShard work for this project since the goal seems the same : porting BlockDS to zig.
In a long term, I wish I could write my own NDS engine in zig, just for the sake of learning, but I think it will stay a wish for a long time :).

**Comment by dedesite** [comment]
Ok, I just tried to build the sample and realized the problem was is those lines in the build system :
```zig
obj.addIncludePath(b.path(b.pathJoin(&.{ "../", blocksDsDir, "/libs/libnds/include/" })));
obj.addIncludePath(b.path("../opt/wonderful/toolchain/gcc-arm-none-eabi/include"));
obj.addIncludePath(b.path("../opt/wonderful/toolchain/gcc-arm-none-eabi/arm-none-eabi/include"));
```

Thoses path are wrong. I wanted to use absolute paths but `addIncludePath` only accepts relative paths, so for this to work, you'll have to adapt the relative path (here `../`) to your file system hierarchy.
I don't really understand why I can't use absolute path, I think I need to learn more about zig build system. I'm just tinkering with zig time to time and lack a real expertise.

**Comment by dedesite** [comment]
Ok, just found out how to include absolute path. It should work now.
